Don't error if hydra parses the result as json but extract it and log it, fixes #30, fixes #37
flywheelsports/hydra-cli pull request #43
Opened 2020-08-08 14:29 UTC by Technikkeller

2020-08-09 15:33 UTC, cjus requested changes
PR looks good. Thanks for this!  Can you make slight changes to the submitted code in order to keep the format consistent. 

* Space after `if` 
* Avoid single line comments - use curly braces

Super minor I know. I'm happy to accept the changes and then reformat the code. Let me know. Thanks again.

2020-11-21 18:21 UTC, Technikkeller commented
sure, sorry I was offline for so long

2020-11-21 18:29 UTC, Technikkeller commented
maybe add eslint or sth tho

2020-11-22 15:28 UTC, cjus commented
@Technikkeller thanks for this. Merging...

2020-11-22 15:28 UTC, merged